apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fcc-drs-test

resources:
  - ../../base
  - route.yaml

# Set newName to your CERN GitLab registry path and update newTag before each deploy.
images:
  - name: fcc-drs
    newName: gitlab-registry.cern.ch/hep-fcc/fcc-drs
    newTag: latest
