apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fcc-drs
  labels:
    app: fcc-drs
spec:
  host: fcc-drs-test.web.cern.ch
  to:
    kind: Service
    name: fcc-drs
  port:
    targetPort: 5050
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
